on:
  push:
    branches:
      - main

env:
  CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
  TF_VAR_account_id: ${{ secrets.ACCOUNT_ID }}
  TF_VAR_zone_id: ${{ secrets.ZONE_ID }}

jobs:
  setup-terraform:
     runs-on: ubuntu-latest
     steps:
       - name: checkout
         uses: actions/checkout@v6
       - name: setup terraform
         uses: hashicorp/setup-terraform@v4
       - name: initialize terraform
         run: terraform init
         working-directory: ./infra
       - name: plan
         run: terraform plan
         working-directory: ./infra
       - name: apply
         run: terraform apply -auto-approve
         working-directory: ./infra
